### ISSUE TITLE
Expose step_count in agent/step/host functions

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#266]
The current step count should be exposed to the user via the various FLAMEGPU api objects. 

I.e. 
+ in agent functions, the user should be able to access the number of steps that have occured (device)
+ in step/host/exit functions, the user should be able to access the number of steps that have occured (host)
+ init functions (shouldn't) need this - they *should* only ever run when `step_count == 0`

`step_count` should be 0 indexed, and refer to the start of the current iteration.

Within submodels, `step_count()` will be relative to the submodel. If it needs to know about the parent models step, this could be calculated in the parent model and stored in an environment variable, mapped into the submodel by the user.

If `--steps 3`:

| function_type   | Iteration 0 | Iteration 1 | Iteration 2 |
|-----------------|-------------|-------------|-------------|
| Init function   |           0 |         N/A |         N/A |
| agent condition |           0 |           1 |           2 |
| agent function  |           0 |           1 |           2 |
| host function   |           0 |           1 |           2 |
| step function   |           0 |           1 |           2 |
| exit condition  |           0|           1 |           2 |
| exit function   |         N/A |         N/A |           3 |

### Todo

+ [x] Increment `step_count` as late as possible in `CUDAAgentModel->getStepCounter()`.
+ [x] Expose `step_count` on the host `flamegpu_host_api`
+ [x] Expose `step_count` on the device via `flamegpu_deivce_api.h`
+ [x] Call methods `getStepCounter` to be consistent with `Simulation::getStepCounter()`
+ [x] Tests
    + [x] Test device getStepCounter() in agent function
    + [x] Test device getStepCounter() in agent func condition
    + [x] Test device getStepCounter() in RTC agent function
    + [x] Test host getStepCounter() in init func (==0)
    + [x] Test host getStepCounter() in host layer func (not incremented yet)
    + [x] Test host getStepCounter() in step func (not incremented yet
    + [x] Test host getStepCounter() in exit func
    + [x] Test host getStepCounter() in exit condition

**Comment by Robadob** [comment]
Presumably, should be stored with a reserved name in environment.
