### ISSUE TITLE
Swig Linux Issue

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#334]
## Todo

+ [x] Add `SWIGWORDSIZE64` definition for not MSVC
+ [x] Require Swig 4
    + [x] if not found on linux, download and build? will add several minutes to configure time (as it must be done at configure time, for findSwig to then work.
    + [x] Make sure this works on Ubuntu CI
    + findSwig expects `SWIG_DIR` and `SWIG_EXECUTABLE` to be set and available at configure time. 
+ [x] Remove requirement of PythonLibs which looks for py2 (Ubuntu 20.04)
+ [x] Stop `BUILD_SWIG_PYTHON_VIRTUALENV` being a thing - I don't see a reason to not support it. 

## Discussion

Currently swig doesn't build under linux. 

This is partially due to an issue with swig on systems where `long` is 64 bit. 

This can be resolved by defining `SWIGWORDSIZE64` before `%include`ing the swig `.i` files, but this must not be done on windows, so either use `#ifdef` or pass to the compiler on linux via cmake.

I..e above `//string support`

```
#if !defined(_MSC_VER)
#define SWIGWORDSIZE64
#endif
```

This however then leads to a compilation error in `flamegpuPYTHON_wrap.cxx`:

```
/home/ptheywood/code/flamegpu/flamegpu2_dev/build/swig/python/Release/pyflamegpu/flamegpuPYTHON_wrap.cxx(248840): error: no operator "=" matches these operands
            operand types are: SwigValueWrapper<std::unordered_map<std::__cxx11::string, EnvironmentDescription::PropData, std::less<std::__cxx11::string>, std::allocator<std::pair<const std::__cxx11::string, EnvironmentDescription::PropData>>, std::allocator<std::pair<const std::__cxx11::string, EnvironmentDescription::PropData>>>> = const std::unordered_map<std::__cxx11::string, EnvironmentDescription::PropData, std::hash<std::__cxx11::string>, std::equal_to<std::__cxx11::string>, std::allocator<std::pair<const std::__cxx11::string, EnvironmentDescription::PropData>>>
```

This corresponds to the line

```
      result = ((EnvironmentDescription const *)arg1)->getPropertiesMap();
```

Where `result` is

```
  SwigValueWrapper< std::unordered_map< std::string,EnvironmentDescription::PropData,std::less< std::string >,std::allocator< std::pair< std::string const,EnvironmentDescription::PropData > > > > result;
```

So the difference appears to be assigning a `const std::unordered_map<...>>` to a `SwigValueWrapper<std::unordered_map<...>>`. Unsure how to proceed with this.

**Comment by ptheywood** [comment]
Commenting out all mention of `EnvironmentDescription` from `flamegpu.i` allows `pyflamegpu` to build under linux, so it's specific to EnvironmentDescription, and appears to be caused when `%include "flamegpu/model/EnvironmentDescription.h"` is present wihtout any other reference.

Looking at the error some more, the `result` has distinctly separate template arguments within the `unordered_map` then the value which is attempting to be assigned. With the ttemplated types split over multiple lines its more obvious what the difference is.

```

SwigValueWrapper<
    std::unordered_map<
        std::__cxx11::string,
        EnvironmentDescription::PropData, 
        std::less<
            std::__cxx11::string
        >, 
        std::allocator<
            std::pair<
                const std::__cxx11::string, 
                EnvironmentDescription::PropData
            >
        >, 
        std::allocator<
            std::pair<
                const std::__cxx11::string, 
                EnvironmentDescription::PropData
            >
        >
    >
>

const std::unordered_map<
    std::__cxx11::string, 
    EnvironmentDescription::PropData, 
    std::hash<
        std::__cxx11::string
    >, 
    std::equal_to<
        std::__cxx11::string
    >, 
    std::allocator<
        std::pair<
            const std::__cxx11::string, 
            EnvironmentDescription::PropData
        >
    >
>
```

After some more digging, it appears that swig 3 doesn't support unordered maps, where swig 3 (3.0.12) is the version available wihin the ubunut repositories (ubuntu < 20.04) , so looks like we will be requiring swig 4 at least. 

> swig-3.0.12 does not have support for std::unordered_map, but swig-4.0.0 will. I have just made a change so that your example works.

https://github.com/swig/swig/issues/1319

**Comment by ptheywood** [comment]
CMakeLists.txt for swig currently searches for the `PythonLibs` package prior to searching for python3. 

This causes issues on 20.04 where python2 is not installed. This doesn't appear to be required / at the very least it shouldn't be looking for the python2 libraries.

From the swig 3.0.12 documentation:

> SWIG supports the new C++ syntax changes with some minor limitations in some areas such as decltype expressions and variadic templates. Wrappers for the new STL types (unordered_ containers, result_of, tuples) are incomplete. The wrappers for the new containers would work much like the C++03 containers and users are welcome to help by adapting the existing container interface files and submitting them as a patch for inclusion in future versions of SWIG.

http://www.swig.org/Doc3.0/CPlusPlus11.html

This implies that in general swig 3 isn't suitable for c++11 (nevermind c++14 which is our current standard), so we probably need to enforce swig >= 4, which will require either cmake magic to download and build, or instructions for installation.
Personally I'm in favour of user-installation, as swig 4 takes a decent length of time to build, so would be better to avoid that from any time that the build directory is removed.



Swig needs to be available at configure time for FindSwig to work (and check the version). 

On windows, Swig is just downloaded as an executable (currently via external_project). 

On linux, it will need to be downloaded if unavailable / insufficient version, then configured, made and installed (to a local location which the user will have access to. 

I.e. from the download location  

```
 ./configure --prefix /path/to/install/loc/
make -j `nproc`
make install
```

The install phase is required, as the executable looks for files realtive to the value of `--prefix`

**Comment by ptheywood** [comment]
Closed by #351
