### ISSUE TITLE
Feature: RNG in agent functions

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#50]
Use curand for random number generation in agent functions when requested.

Should be seedable from the host.

**Comment by ptheywood** [comment]
Providing multiple distributions would also be useful (uniform, normal etc)

**Comment by Robadob** [comment]
This might be a useful base to build out from/fork.

https://gist.github.com/Robadob/33fcb8a63293f02f231a1f5e0ef41536

**Comment by Robadob** [comment]
**TODO:**
* `Sim/Simulation` (Controls definition of simulation)
  + [ ] `checkArgs()`: Update to parse for seed.
  + [ ] `seedRandom()`: Add programmatic method to control random seed.
* `gpu/CUDAAgentModel` (Controls execution of model)
  + [ ] `step()`: Resize (and init) curand state array on population changes.
+ [ ] `runtime/util/AgentRandom`  : Include public object for accessing random functionality
  + [ ] `uniform<Type>()` (`float`/`double` methods, mirrored from curand api)
  + [ ] `normal<Type>()`
  + [ ] `logNormal<Type>()`
  + [ ] `poison()` (only available as float)
  + [ ] `uniform<int>()` (convenience wrapper to provide `int` generation)
+ [ ] `runtime/utility/Random` : Include private static-object for setting up/initialising curand states
  * Vars:
    + [ ] `__device__ curandState *random_state`
    + [ ] `__device__ size_type random_size` (might not be able to use size type here)
  * Member Vars:
    + [ ] `unsigned long long seed`
    + [ ] `size_type length`
    + [ ] `float shrinkModifier`
    + [ ] `float growthModifier`
  * Methods:
  + [ ] `void init(const unsigned long long &seed)` (Initially sets up `__device__` vars)
  + [ ] `size_type size()`
  + [ ] `void setExtendModifier(float)` (Controls rate of growth, e.g. 2x, 1.5x, must be greater than 1.0)
  + [ ] `float getExtendModifier()`
  + [ ] `void setShrinkModifier(float)` (Controls rate of shrink, e.g. 0.5x, must be <=1, >0)
  + [ ] `float getShrinkModifier()`
  + [ ] `bool setSize(size_type len)` (Returns true if size was changed according to grow/shrink rules)
* `runtime/flame_functions_api.h` (Provides access inside agent functions to FLAMEGPU methods)
  + [ ] Make `Random` accessible somehow.
* Tests
  + [ ] Example usage in a model
  + [ ] Actual unit tests (?)
* Documentation/User Guide
